version: "3.8"
services:
    db:
        image: postgres:14.1-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - ./src/config/db/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    api:
        container_name: hurb-api
        build:
            context: ./
        image: hurb-api
        depends_on:
            - db
        ports:
            - 3000:3000
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: postgres
        links:
            - db
        volumes:
            - "./:/src"
volumes:
    db:
        driver: local
